version: '3.1'
services:
  backup:
    build: .
    environment:
      - HOST=${HOST:?err}
      - CREDENTIALS=${CREDENTIALS:?err}
    volumes:
      - "./servers.json:/app/servers.json"
      - "~/.ssh:/root/.ssh"